### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by longngn** [CardanoSolutions/kupo#1]
#### Describe your idea, in simple words.

Many infra management tools like K8s rely on a health check endpoint of service to schedule restart or do alerting. I guess we can `GET /v1/checkpoints` but not sure if that's hacky.

#### Why is it a good idea?

It'll be more compatible with existing infrastructures. Ogmios also has a `/health` endpoint.

#### Are you willing to work on it yourself?

I haven't dug much into the codebase to understand what should be considered healthy for Kupo.

**Comment by KtorZ** [comment]
The `GET /v1/checkpoints` isn't hacky at all, it's meant to monitor the progress of the underlying syncing process. However, that's more about progress reporting than about health.

I agree that a health endpoint (and command, for containers) would be nice also.
