### ISSUE TITLE
Most recent node tip of Kupo may get stuck

### ISSUE THREAD

**Issue by nielstron** [CardanoSolutions/kupo#143]
### What Git revision / release tag are you using?
2.7.0+41ae67

### Describe what the problem is?
Same as #142 
It is unfortunately not resolved by upgrading to  kupo 2.7.0

```bash
$ curl localhost:1482/health
# TYPE kupo_connection_status gauge
kupo_connection_status  1.0
# TYPE kupo_most_recent_checkpoint counter
kupo_most_recent_checkpoint  107274767
# TYPE kupo_most_recent_node_tip counter
kupo_most_recent_node_tip  107274767
$ curl localhost:6666/health
# TYPE kupo_connection_status gauge
kupo_connection_status  1.0
# TYPE kupo_most_recent_checkpoint counter
kupo_most_recent_checkpoint  107257239
# TYPE kupo_most_recent_node_tip counter
kupo_most_recent_node_tip  107257239
```

### What should be the expected behavior?

The most recent node tip should always refer to the actual most recent node tip.

### If applicable, what are the logs from the server around the occurence of the problem?

The respective log from kupo
```
Nov 01 07:49:51 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:51.965094591Z","thread":"379893","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":5134,"retryingIn":0.1}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:51 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:51.995123761Z","thread":"380244","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":1427,"retryingIn":0.25}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:52.066252366Z","thread":"379893","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":5135,"retryingIn":0.1}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:52.160340692Z","thread":"379902","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":2056,"retryingIn":0.25}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:52.16747226Z","thread":"379893","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":5136,"retryingIn":0.1}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:52.245537436Z","thread":"380244","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":1428,"retryingIn":0.25}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Warning","timestamp":"2023-11-01T07:49:52.268632358Z","thread":"379893","message":{"Database":{"tag":"DatabaseConnection","message":{"tag":"ConnectionBusy","attempts":5137,"retryingIn":0.1}}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Notice","timestamp":"2023-11-01T07:49:52.305537426Z","thread":"14","message":{"Gardener":{"tag":"GardenerExitGarbageCollection","totalPrunedRows":147695}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:52 ns366159 bash[2889517]: {"severity":"Notice","timestamp":"2023-11-01T07:49:52.305640449Z","thread":"14","message":{"Gardener":{"tag":"GardenerBeginGarbageCollection","pruning":"binary_data"}},"version":"v2.7.0+41ae67"}
Nov 01 07:49:55 ns366159 bash[2889517]: {"severity":"Notice","timestamp":"2023-11-01T07:49:55.888146796Z","thread":"12","message":{"Consumer":{"tag":"ConsumerRollBackward","point":107257204}},"version":"v2.7.0+41ae67"}

```

The current time when fetching this log and seeing the tip difference was 12:15 UTC

**Comment by nielstron** [comment]
Also interesting: just happened that the most recent node tip < most recent checkpoint (but both behind the correct time)
```
$ curl localhost:6667/health
# TYPE kupo_connection_status gauge
kupo_connection_status  1.0
# TYPE kupo_most_recent_checkpoint counter
kupo_most_recent_checkpoint  107265870
# TYPE kupo_most_recent_node_tip counter
kupo_most_recent_node_tip  107276161
```

**Comment by KtorZ** [comment]
Hey, 

1. Are you sure that your node is actually synchronized? 
2. Could you run Kupo with an additional `--log-level debug`?
3. Are you able to query the instance for matches and other stored elements in this situation? 
4. Are you able to run `sqlite3 [FILEPATH.sqlite3] ".indexes"` on your database and forward the result? 

Some of your connection have an extremely high number of failed attempts. Which is rather odd. Some are even just failing to open (250ms is the retry delay on open). It might be necessary to ALSO prune binary_data incrementally (incremental deletion only happen for rollbacks and inputs pruning so far) so avoid keeping the database busy for too long. The high `--gc-interval` and multiple unsuccessful pruning have likely led to that situation.

**Comment by Saghen** [comment]
We've noticed a similar issue on Kupo v2.7.0 where garbage collection on `binary_data` with `--prune-utxo` takes 10-15 minutes

Arguments: `--node-socket /ipc/node.socket --node-config /config/cardano-node/config.json --host "0.0.0.0" --workdir /data/db --since origin --match "*/*"  --prune-utxo`

```
{"severity":"Notice","timestamp":"2023-11-20T22:48:47.895743118Z","thread":"13","message":{"Gardener":{"tag":"GardenerBeginGarbageCollection","pruning":"binary_data"}},"version":"v2.7.0+41ae67"}
{"severity":"Notice","timestamp":"2023-11-20T23:00:34.770557484Z","thread":"13","message":{"Gardener":{"tag":"GardenerExitGarbageCollection","totalPrunedRows":822}},"version":"v2.7.0+41ae67"}
```

**Comment by Saghen** [comment]
Here's the debug logging excluding health checks (via `rg -v HttpRequest | rg -v HttpResponse`... hopefully doesn't exclude anything important): https://paste.super.fish/p/9Y3mCS.txt

**Comment by KtorZ** [comment]
Thanks a lot @Saghen; I am a bit overloaded lately but I will look into it by next week the latest. One last question, I take from the command above that you aren't running with a *special* gc-interval, but using the default one?

**Comment by Saghen** [comment]
Sounds good! And yep, using the default interval

**Comment by nielstron** [comment]
Reporting that kupo mainnet still is choking on the pruning (limited to 50k rows now)

```

**Comment by KtorZ** [comment]
> Would it make sense to make the pruning increment size a command line option?
No.

I am surprised however by the time you're reporting. I've tested this on a dev machine which took less than 30s per batch, with 1.5M entries to delete. 

What are the specs of the machine you're running this by?

**Comment by Saghen** [comment]
We're seeing similar behavior as Niels; Garbage collection took 15 minutes and stalled the syncing. We're running with 2 cores, 2GB RAM and NVME.

**Comment by KtorZ** [comment]
As identified in another discussion, Kupo is missing one crucial database index somehow. This got probably lost in some refactoring and failed to be caught by tests. 

So right now, you may want to run (offline):

```
sqlite3 your/working/dir/kupo.sqlite3 "CREATE INDEX IF NOT EXISTS inputsByDatumHash ON inputs(datum_hash)"
```

This should take a minute or so, and solve the GC issue for now. A single GC increment should take no more than a minute. And given that you probably have a lot of data to clean up from previously interrupted GC, it'll take several minutes / hours to clear everything down. Though synchronization should be interleaved without problem.

**Comment by biofreeze** [comment]
Just to double check, we should be running the following command manually each time we do a sync yes?
```sql
sqlite3 your/working/dir/kupo.sqlite3 "CREATE INDEX IF NOT EXISTS inputsByDatumHash ON inputs(datum_hash)"
```

I noticed that if you start a sync with the `--defer-db-indexes` option, it will actually remove that index. 

<img width="1108" alt="Screenshot 2023-12-30 at 11 24 40 AM" src="https://github.com/CardanoSolutions/kupo/assets/150722054/1092ed4b-7f6f-44a6-827f-313aa0b8e12b">

So i'm assuming we should be starting Kupo, and then manually create the index after it's started, each time? If it's necessary to speed up garbage collection, is there a way this index can not be deleted when we restart Kupo with the `--defer-db-indexes` option?

**Comment by KtorZ** [comment]
Nothing extra is needed since 2.7.2, the issue was fixed.
