### ISSUE TITLE
Kupo throws error when trying to match for stake key

### ISSUE THREAD

**Issue by bakon11** [CardanoSolutions/kupo#161]
### What Git revision / release tag are you using?
2.8.0

### Describe what the problem is?

When trying to run kupo with match of specific stake key: "stake_1uxcf8uzykaljlvfuuxpge92trpv2e8mkjd08fcu3csj4uustv529u"

when I use the stake key in the example it work fines: "stake_vkh14hkp0sncfkt76spuqydtww4r900hfmsseezztzlh9sjkkjx6d7q"

I also noticed the example stake key is one character longer than any stake I can produce.
`stake_1uxcf8uzykaljlvfuuxpge92trpv2e8mkjd08fcu3csj4uustv529u`
`stake_vkh14hkp0sncfkt76spuqydtww4r900hfmsseezztzlh9sjkkjx6d7q`

Thank you.

### If applicable, what are the logs from the server around the occurrence of the problem?

```option --match: cannot parse value `*/stake_1uxcf8uzykaljlvfuuxpge92trpv2e8mkjd08fcu3csj4uustv529u```

Thank you.

**Comment by bakon11** [comment]
ahh I figured it out, instead of providing the pattern:  
```--match "*/stake_1uxcf8uzykaljlvfuuxpge92trpv2e8mkjd08fcu3csj4uustv529u"```

I only used the stake key. ```--match "stake1uxcf8uzykaljlvfuuxpge92trpv2e8mkjd08fcu3csj4uustv529u"```

**Comment by KtorZ** [comment]
Indeed, when bech32 prefix is `stake`, it indicates a full stake address and thus needs to be provided in full. This is different from a stake key which is prefixed with `stake_vk` or a stake key hash which is prefixed with `stake_vkh`. 

The latter are only found within addresses, associated with payment credentials and thus must be provided alongside a payment credential pattern. 

Note that in bech32, the prefix is given by everything that precedes the digit `1` which always only appear once in bech32 string, and is always a delimiter.

**Comment by bakon11** [comment]
Ahhh yeah that makes perfect sense, I totally missed the stake_vk and stake_vkh patterns in the docs.

Thank you!!
