### ISSUE TITLE
Support Cardano Node 9.0.0

### ISSUE THREAD

**Issue by dedicatednodes** [CardanoSolutions/kupo#177]
### What is your idea? Provide a use case.
Support the new Cardano Node version 9.0.0 to be reach for the Chang hard fork.

### Why is it a good idea?
To avoid this great software piece from becoming irrelevant.

### What is the current alternative and why is it not good enough?
Not relevant.

**Comment by KtorZ** [comment]
Noted.

**Comment by gilligan** [comment]
@KtorZ sorry for pinging you on this closed ticket, but could you share some insights on node 9.0.0 compatibility?

I reckon the latest release isn't compatible? Do you already know if upgrading for compatibility will entail any major changes and thus effort for you?

thanks a lot!

**Comment by KtorZ** [comment]
@gilligan In principle, it _ought to_ be compatible. Up to the Conway era. There are yet-another-set of breaking changes that are part of Conway, so Kupo would likely choke on the first block from the Conway era. Other than that, and unless the core team at IntersectMBO / InputOutput decided (purposely or accidentally) to break the communication protocols (which has happened in the past), it should keep working just fine.

**Comment by KtorZ** [comment]
Note: I close the ticket from @dedicatednodes because that's simply not a way to ask for something like this. It feels a bit too much like an order -- which I'd happily take from a client/customer or a recurring contributor, but refuse to do from someone who hasn't remotely interacted with or supported the project in the past. This is just unacceptable. Especially when it 4+ years of delivering software solutions for the Cardano Stack, Ogmios & Kupo has generally (always?) been updated for compatibility within 2 weeks of the node's release. 

I don't have the bandwidth right now to test the compatibility between latest Kupo & 9.0.0, but if someone does, I am happy to hear about any shortcomings.

**Comment by gilligan** [comment]
> Note: I closed the ticket from @dedicatednodes because that's simply not a way to ask for something like this. It feels a bit too much like an order

All good, I completely understand and sympathize with your frustration and this all-too-common experience as a F/OSS maintainer ... i can only extend thanks from my side about the work you've done in the past. Much appreciated.

> I don't have the bandwidth right now to test the compatibility between latest Kupo & 9.0.0, but if someone does, I am happy to hear about any shortcomings.

We had some folks give kupo a try with https://sancho.network/ and unfortunately it seems like there are some problems. Quoting one of our Test Engineers:

```
" [...] but I just verified it on Sanchonet, which has already forked to Conway era.
DBSync stopped syncing on epoch 392 (currently 396) and kupo also stopped
syncing at slot 33955213 (currently 34458348 )"
```

I heard you on not having capacity at the moment but is there any further info we could provide or are there any hints from your end? We are finding ourselves in a bit of a pickle with this one 😂

**Comment by KtorZ** [comment]
Yes, so as expected, the Conway era is not going to be supported _yet_. I can probably get a working build relatively fast; I've been through it for Ogmios lately, and Kupo is an order of magnitude easier to upgrade. Problem is that there are also other bits in flux that makes it unpractical to cut a release right away. 

But if you're fine working out of the `master` branch -- at least on Sancho, then that's an option.

**Comment by gilligan** [comment]
> But if you're fine working out of the master branch -- at least on Sancho, then that's an option.

Ah, i hadn't even thought of that. Thanks for that insight! We'll give that a try! 👍

**Comment by KtorZ** [comment]
@gilligan turns out it was pretty trivial to update :), it helps to have an internal anti-corruption layer. 

--> https://github.com/CardanoSolutions/kupo/commit/cef34dcf6e42391e30b466c3b1e4b3867745e5fd
