### ISSUE TITLE
Is `?spent` strictly openapi compliant?  

### ISSUE THREAD

**Issue by waalge** [CardanoSolutions/kupo#179]
Is `?spent` strictly openapi compliant?  

https://github.com/OAI/OpenAPI-Specification/issues/1782

I confess to not understanding the openapi spec despite having read it many times

Im struggling to get tooling to accept a flag with no value. I regret my choices of dependencies...

**Comment by KtorZ** [comment]
Arguably, it is, though it's _not recommended_

> If true, clients MAY pass a zero-length string value in place of parameters that would otherwise be omitted entirely, which the server SHOULD interpret as the parameter being unused. Default value is false. If [style](https://spec.openapis.org/oas/latest.html#parameter-style) is used, and if [behavior is n/a (cannot be serialized)](https://spec.openapis.org/oas/latest.html#style-examples), the value of allowEmptyValue SHALL be ignored. Interactions between this field and the parameter’s [Schema Object](https://spec.openapis.org/oas/latest.html#schema-object) are implementation-defined. This field is valid only for query parameters. Use of this field is NOT RECOMMENDED, and it is likely to be removed in a later revision.
