### ISSUE TITLE
Node socket vs Ogmios?

### ISSUE THREAD

**Issue by bakon11** [CardanoSolutions/kupo#33]
Is there any advantage in performance or anything by connecting Kupo to Cardano node socket vs Ogmios instance?

**Comment by KtorZ** [comment]
Yes. 

- It is much faster (~2x) to synchronize directly through the node's domain socket than through Ogmios.
- But, synchronizing through the websocket allows quite easily to do it remotely and for instance, have multiple kupo services connected to a single instance, all on different machines.

**Comment by bakon11** [comment]
Awesome, thank you.
