### ISSUE TITLE
Allow specifying a slot with the `spent` query parameter

### ISSUE THREAD

**Issue by Quantumplation** [CardanoSolutions/kupo#37]
#### Describe your idea, in simple words.

Allow specifying either `?spent=12345` (to reuse the existing parameter) or `?spent_since=12345` (to introduce a new parameter) to return all unspent UTXOs, plus those that have been spent *after* a given slot.

#### Why is it a good idea?

The result set of `/matches` grows without bound; you can resolve this and bound the size of the result set by specifying `--prune-spent` or `?unspent` to see only the current UTXO for that wallet.

However, many applications need to respond the spending of a specific UTXO: sending a warning email, updating an internal data structure, logging, etc.

Allowing an application to keep spent UTXOs, but only return those that have been spent since the last time kupo was queried would bound the result set size, while still allowing access to data about the spend events (namely, the block / slot it was spent in).

(Note: this solves a similar problem to #36, but I submitted them as separate issues for separate discussion / implementation)

#### Are you willing to work on it yourself?
Willing? Yes.  Able? Probably not.

**Comment by KtorZ** [comment]
As note: I feel more inclined towards #36 at this stage. Looks less pervasive / opinionated to implement and should give the same capability in the end.

**Comment by KtorZ** [comment]
Made redundant by #36.
