### ISSUE TITLE
`--prune-utxo` is not safe

### ISSUE THREAD

**Issue by nielstron** [CardanoSolutions/kupo#44]
#### What Git revision are you using? 
1278955a8b1c33e55c2b4d79bed374609355f5a2

#### Describe what the problem is? 
Enabling the `--prune-utxo` flag does delete results from the database the moment a spending output is discovered on chain. This is problematic because it might be that the chain has to roll back and the spending output disappears from the chain. In that case, the database is missing results that still exist on-chain.

Following situation illustrates the issue:
- addr1 has UTxO A as of block 1
- A is spent in block 3 (kupo deletes A discovering this)
- the blockchain rolls back to block 2 because blockchain things happen
- kupo does roll back to block 2 but fails to restore A as it has been created in block 1 which is never touched again

#### What should be the expected behavior?

After the rollback, kupo needs to restore those UTxOs that have not been spent due to the rollback.

#### Fixes considered

As discussed with @KtorZ the best way to go about this is to only delete results from the database when the consensus protocol guarantees that they have been spent, and that this spending operation is immutable. This ought to be the case if the block that spent a UTxO is at least `k = 2160` deep in the chain.

`--prune-utxo` is supposed to reduce memory consumption of the database. Arguably keeping spent UTxOs for at most 2160 blocks into the future should not cause trouble on most setups. For adventurous souls with tight memory constraints it may be considered to make `k` a parameter for kupo. However it is important to note that this puts the DB representation of the UTxO set at high risk of  being corrupted.

**Comment by KtorZ** [comment]
@nielstron do you have any _relatively reproducible_ setup to try this out? The issue should be fixed on #42 now, with the garbage-collector only removing inputs that are old enough to be considered _truly deleted_. I don't have good ways to test that easily e2e though.

**Comment by KtorZ** [comment]
This has been truly fixed as part of #45
