### ISSUE TITLE
Pattern input accepting policy_id and asset_name

### ISSUE THREAD

**Issue by 1000101** [CardanoSolutions/kupo#56]
#### Describe your idea, in simple words.
Hi there! Would it be possible to use `policy_id` (+ optionally `asset_name`) as a pattern input?
e.g.:
-  querying all txs of a given policy/asset
-  querying addresses that hold a given asset (basically UTxOs including a given policy/asset)

#### Why is it a good idea?
Querying the data from dbsync currently takes more than 5 minutes for assets such as:
`a0028f350aaabe0545fdcb56b039bfb08e4bb4d8c4d7c3c7d481c235484f534b59`.

#### Are you willing to work on it yourself?
I wish I knew Haskell.

Thanks for your consideration and the amazing work you've already done!!!

**Comment by KtorZ** [comment]
CC @mmahut
