### ISSUE TITLE
Add inline datum field to rest API

### ISSUE THREAD

**Issue by will991** [CardanoSolutions/kupo#64]
#### Describe your idea, in simple words.
The current response object for matches that can be retrieved via the rest API does not hold inline-datums of outputs. It would be great to return it.

#### Why is it a good idea?
Allows full access to the record stored on-chain.

#### Are you willing to work on it yourself?
Not much expertise in Haskell. No.

**Comment by KtorZ** [comment]
Hey!

You can access datums through the [`/datums` endpoints group](https://cardanosolutions.github.io/kupo/#tag/Datums/paths/~1datums~1{datum-hash}/get). Any datums that have been seen by the indexer, and whose hash is present in a match result can be fetched from the server. Said differently, you can retrieve any inline-datum immediately, and referenced datums only as soon as they're seen in a transaction (some Dapps do include them when they first create the output, in which case they're immediately available but others do only specify it when necessary -- i.e. when spending).

**Comment by will991** [comment]
Thanks! I didn't even check that endpoint. That makes sense - I'll close this issue!
