### ISSUE TITLE
Ensure stable ordering of results within a same slot / block

### ISSUE THREAD

**Issue by 1000101** [CardanoSolutions/kupo#65]
#### Describe your idea, in simple words.
When there are multiple transactions in the same block, the ordering becomes non-deterministic. This can be problematic in multi-node setup, when multiple instances of kupo may return data in different ordering and there is currently no good way of ordering them. Cardano-db-sync solves this by `block_index` field. Introducing `block_index` would resolve this.

#### Why is it a good idea?
To be able to retrieve txs ordered in a deterministic fashion.

Thanks for considering this :sparkles: !!!

**Comment by KtorZ** [comment]
Let's go.
