### ISSUE TITLE
Protect against changing server options

### ISSUE THREAD

**Issue by james-iohk** [CardanoSolutions/kupo#8]
#### Describe your idea, in simple words.
Add a way for Kupo to protect itself against being started with different options when restoring from a db.

#### Why is it a good idea?
It is possible to start building a db and then restart Kupo with different match and since options. This causes it to appear the same as a server started with matching options but its db state is different. One can measure db size as a quick indication of this.

#### Are you willing to work on it yourself?
No

**Comment by KtorZ** [comment]
There's already guards in place for the `--since` option indeed! I intend to add similar guards for patterns. This will be tackled as part of #3 as patterns will be also stored in the database.
