### ISSUE TITLE
Documentation on rollbacks. 

### ISSUE THREAD

**Issue by waalge** [CardanoSolutions/kupo#87]
How does kupo handle rollbacks? 

Out of my depth here. 
I assume that there are cases where the data provider (node or ogmios?) 
change their mind about whether some previously handed over set of blocks are actually on-chain. 
I did a quick search for "roll" here and in the docs, but I can't extract an answer to 
"What happens when ... " 

Will entries appear in a `matches` response before a rollback, and then be removed from the kupo db on rollback, so no longer appear?

**Comment by KtorZ** [comment]
Good question, and I am tempted to **not** answer it right here but instead, write a bit of documentation about it and refer to it. Which I'll do. 

In the meantime, a short answer is: Kupo handles rollback just fine and gives you mechanisms for working with them too (such as the `X-Most-Recent-Checkpoints` header). There's a bit of documentation on this topic in the description of the `limit` request parameter for [putPattern](https://cardanosolutions.github.io/kupo/#operation/putPattern). 

I'll add a section in the user guide about this topic, and I'll appreciate your feedback on it.

**Comment by waalge** [comment]
Thanks! 

(And also for the `rollback_to` option :rocket: )

**Comment by KtorZ** [comment]
https://cardanosolutions.github.io/kupo/#section/Rollbacks-and-chain-forks

**Comment by waalge** [comment]
c'est parfait. merci
