### ISSUE TITLE
Unexpected error message when missing the workdir folder

### ISSUE THREAD

**Issue by mpizenberg** [CardanoSolutions/kupo#94]
#### What Git revision are you using? 

I'm using the `v2.2.1` release for linux

#### What operating system are you using, and which version?

- [x] Linux / archlinux

#### Describe what the problem is?

I got an unexpected error message when starting kupo:

```
❯ kupo \
        --node-socket ~/programs/cardano-node-1.35.4-linux/mainnet/db/node.socket \
        --node-config ~/programs/cardano-node-1.35.4-linux/configuration/cardano/mainnet-config.json \
        --since origin \
        --defer-db-indexes \
        --match "*/stake_vkh14hkp0sncfkt76spuqydtww4r900hfmsseezztzlh9sjkkjx6d7q" \
        --workdir ./db
kupo: SQLite3 returned ErrorCan'tOpen while attempting to perform open "file:./db/kupo.sqlite3?mode=rwc": unable to open database file
```

#### What should be the expected behavior?

I figured that I simply needed to create the `db` workdir I'm passing as argument. I would have expected kupo to check for the existence of the workdir and either tell me it does not exist or create it itself. I wasn't expected to reach a crash with the a default sqlite error message.

**Comment by KtorZ** [comment]
Good point.

**Comment by KtorZ** [comment]
Alternatively: we could try to create the folder path recursively if it's not there.
